import Image from "next/image";
import { Header } from "@/components/Header";
import { QuantityOrder } from "@/components/OrderButton";
import { formatNpr, product } from "@/lib/product";

const testimonials = [
  ["Practical for everyday security", "The pan-and-tilt view makes it much easier to cover the room than a fixed camera."],
  ["Simple app controls", "I can check in from my phone and use the two-way talk feature whenever I need it."],
  ["Clear picture, day and night", "The image is clear and night visibility gives me more confidence after dark."],
];
const faqs = [
 ["What is included?", "The camera unit, its standard accessories, and setup guidance. Please confirm the exact box contents with our sales representative."],
 ["Can I use it with my phone?", "Yes. You can control and view the camera using the EZVIZ app on Android and iOS."],
 ["Does it work at night?", "Yes. It supports night vision for monitoring in low-light conditions."],
 ["Can it be installed on a wall or ceiling?", "Yes. It can be mounted to a ceiling or wall, or placed normally on a shelf or rack."],
 ["Is delivery free?", "Delivery is free inside the valley. Our representative will confirm delivery details when calling you."],
 ["How do I pay?", "This offer uses Cash on Delivery. Pay only once the order is confirmed and delivered."],
];
export default function Home() { return <><Header /><main>
 <section className="overflow-hidden bg-ink text-white"><div className="mx-auto grid max-w-7xl items-center gap-10 px-5 py-16 md:grid-cols-2 md:py-24"><div><p className="mb-5 inline-block rounded-full bg-yellow-400 px-3 py-1 text-sm font-bold text-black">SMART HOME SECURITY</p><h1 className="max-w-xl text-5xl font-black leading-[.95] tracking-tight md:text-7xl">See every corner. Feel secure.</h1><p className="mt-6 max-w-lg text-lg leading-8 text-white/70">{product.description}</p><div className="mt-8 flex flex-wrap gap-3"><a href="#order" className="rounded-full bg-yellow-400 px-6 py-4 font-bold text-black">Purchase Now</a><a href="#features" className="rounded-full border border-pink-200/50 px-6 py-4 font-bold">Explore features</a></div><div className="mt-10 flex gap-7 text-sm text-pink-100"><span>✓ Cash on Delivery</span><span>✓ Free valley delivery</span></div></div><div className="relative mx-auto aspect-square w-full max-w-lg"><div className="absolute inset-8 rounded-full bg-pink-300/20 blur-3xl"/><Image priority src={product.images[0]} alt="EZVIZ H6c Pro camera" fill className="relative object-contain" sizes="(max-width: 768px) 100vw, 50vw" /></div></div></section>
 <section className="bg-ink px-5 pb-10"><div className="mx-auto max-w-7xl overflow-hidden rounded-3xl border border-pink-200/25 shadow-2xl shadow-pink-400/10"><Image src="/smart-security-banner-peach.png" alt="Smart security for every home" width={1600} height={1000} className="h-auto w-full" priority /></div></section>
 <section id="order" className="mx-auto grid max-w-7xl items-center gap-12 px-5 py-20 lg:grid-cols-2"><div className="relative mx-auto aspect-square w-full max-w-xl overflow-hidden rounded-3xl bg-white shadow-sm"><Image src={product.images[0]} alt="EZVIZ H6c Pro camera" fill className="object-contain p-7" sizes="(max-width: 1024px) 100vw, 50vw" /></div><div className="rounded-3xl border border-black/10 bg-white p-7 shadow-xl shadow-black/5 lg:p-10"><p className="font-bold text-gold">EZVIZ H6c Pro 5MP</p><h2 className="mt-2 text-4xl font-black tracking-tight">360° protection, in one smart camera.</h2><p className="mt-4 leading-7 text-black/60">Full HD/4K-ready smart surveillance features, designed for smooth control at home or work.</p><div className="mt-6 flex items-baseline gap-3"><span className="text-3xl font-black">{formatNpr(product.price)}</span><del className="text-black/40">{formatNpr(product.originalPrice)}</del><span className="rounded-full bg-yellow-100 px-3 py-1 text-sm font-bold">Save Rs. 300</span></div><p className="mt-2 text-sm font-semibold text-green-700">✓ {product.delivery}</p><div className="my-7 h-px bg-black/10"/><QuantityOrder /></div></section>
 <section className="bg-white px-5 py-18" id="reels"><div className="mx-auto max-w-7xl py-16 text-center"><p className="font-bold">SEE IT IN ACTION</p><h2 className="mt-2 text-4xl font-black">A closer look at H6c Pro</h2><div className="mx-auto mt-10 max-w-sm rounded-[2.5rem] border-8 border-pink-200 bg-white p-2 shadow-2xl shadow-pink-300/20"><iframe title="EZVIZ H6c Pro reel" src="https://www.tiktok.com/embed/v2/7650180277410499861" className="h-[560px] w-full rounded-[2rem] bg-white" allow="fullscreen" /></div><p className="mt-5 text-sm text-black/70">Tap play in the video to watch.</p></div></section>
 <section id="features" className="mx-auto max-w-7xl px-5 py-20"><p className="font-bold text-gold">WHY EZVIZ</p><h2 className="mt-2 text-4xl font-black">More awareness. More control.</h2><div className="mt-10 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{product.benefits.map((benefit,i)=><div key={benefit} className="rounded-2xl border border-black/10 bg-white p-6"><span className="text-2xl">{["◉","↻","◌","◐","⌁","⌘"][i]}</span><h3 className="mt-8 text-lg font-bold">{benefit}</h3><p className="mt-2 text-sm leading-6 text-black/60">Built to make day-to-day monitoring clear and effortless.</p></div>)}</div><a href="#order" className="mt-10 inline-block rounded-full bg-ink px-6 py-4 font-bold text-white">Buy Now</a></section>
 <section className="bg-white px-5 py-20"><div className="mx-auto max-w-7xl"><p className="font-bold text-gold">BUILT FOR PEACE OF MIND</p><h2 className="mt-2 text-4xl font-black">What buyers value most</h2><div className="mt-10 grid gap-5 md:grid-cols-3">{testimonials.map(([title,text])=><figure key={title} className="rounded-2xl bg-cream p-7"><div className="text-yellow-500">★★★★★</div><blockquote className="mt-5 text-lg font-semibold">“{text}”</blockquote><figcaption className="mt-5 text-sm font-bold">— {title}</figcaption></figure>)}</div></div></section>
 <section className="mx-auto max-w-4xl px-5 py-20"><p className="font-bold text-gold">NEED TO KNOW</p><h2 className="mt-2 text-4xl font-black">Frequently asked questions</h2><div className="mt-8 divide-y divide-black/10 rounded-2xl border border-black/10 bg-white px-6">{faqs.map(([q,a])=><details key={q} className="group py-5"><summary className="cursor-pointer list-none font-bold">{q}<span className="float-right text-xl group-open:rotate-45">+</span></summary><p className="pt-3 leading-7 text-black/60">{a}</p></details>)}</div></section>
 <section className="bg-ink px-5 py-20 text-center text-white"><h2 className="text-4xl font-black">Protect what matters most.</h2><p className="mx-auto mt-4 max-w-lg text-white/70">Order your EZVIZ H6c Pro today with Cash on Delivery.</p><a href="#order" className="mt-8 inline-block rounded-full bg-yellow-400 px-7 py-4 font-bold text-black">Order Now</a></section>
 </main><footer className="bg-ink px-5 py-8 text-center text-sm text-pink-100/70"><Image src="/ojas-international-logo-final.png" alt="Ojas International" width={270} height={108} className="mx-auto h-20 w-auto object-contain" /><p className="mt-3">Call us: <a className="font-bold text-pink-100" href="tel:9801989840">9801989840</a> · Nayathimi, Bhaktapur</p><p className="mt-2">© {new Date().getFullYear()} OJAS International. Cash on Delivery available.</p></footer></> }
