"use client";
export const dynamic = "force-dynamic";
import Link from "next/link";
import Image from "next/image";
import { useRouter, useSearchParams } from "next/navigation";
import { FormEvent, Suspense, useEffect, useMemo, useState } from "react";
import { formatNpr, product } from "@/lib/product";
import { trackMetaEvent } from "@/lib/metaPixel";

export default function CheckoutPage() { return <Suspense fallback={<main className="min-h-screen bg-cream" />}><CheckoutContent /></Suspense> }
function CheckoutContent() {
 const search = useSearchParams(); const router = useRouter();
 const quantity = Math.max(1, Number(search.get("quantity")) || 1); const price = Number(search.get("price")) || product.price; const productName = search.get("product") || product.name;
 const total = useMemo(()=>quantity*price,[quantity,price]); const [error,setError]=useState(""); const [sending,setSending]=useState(false);
 useEffect(()=>{ trackMetaEvent("InitiateCheckout", { content_name: productName, content_type: "product", value: total, currency: "NPR", num_items: quantity }); },[productName,quantity,total]);
 async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); setError(""); setSending(true); const form = new FormData(e.currentTarget); const body = { name: form.get("name"), phone: form.get("phone"), email: form.get("email"), location: form.get("location"), productName, quantity, pricePerPiece: price, totalPrice: total }; try { const res=await fetch("/api/order",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}); const data=await res.json(); if(!res.ok) throw new Error(data.error || "Unable to submit your order. Please try again."); trackMetaEvent("Purchase", { content_name: productName, content_type: "product", value: total, currency: "NPR", num_items: quantity, order_id: data.orderId }); const query=new URLSearchParams({orderId:data.orderId,product:productName,quantity:String(quantity),total:String(total)}); router.push(`/thank-you?${query}`); } catch(err) { setError(err instanceof Error?err.message:"Unable to submit your order."); setSending(false); } }
 return <main className="min-h-screen bg-cream px-5 py-8"><div className="mx-auto max-w-5xl"><Link href="/" aria-label="Ojas International home"><Image src="/ojas-international-logo-final.png" alt="Ojas International" width={270} height={108} className="h-16 w-auto object-contain" priority /></Link><div className="mt-8 grid gap-8 lg:grid-cols-[1.3fr_.7fr]"><form onSubmit={submit} className="rounded-3xl bg-white p-7 shadow-xl shadow-pink-400/10 md:p-10"><p className="font-bold text-gold">SECURE CHECKOUT</p><h1 className="mt-2 text-4xl font-black">Complete your COD order</h1><p className="mt-3 text-black/60">We’ll call you to confirm before dispatching your order.</p><div className="mt-8 grid gap-5"><Field label="Full Name" name="name" autoComplete="name" required /><Field label="Phone Number" name="phone" type="tel" autoComplete="tel" required /><Field label="Email Address" name="email" type="email" autoComplete="email" required /><div><label htmlFor="location" className="mb-2 block text-sm font-bold">Exact Location</label><textarea id="location" name="location" required placeholder="Kindly share your exact location" className="min-h-28 w-full rounded-xl border border-pink-200 px-4 py-3 outline-none ring-yellow-300 focus:ring-2" /></div></div>{error&&<p role="alert" className="mt-5 rounded-xl bg-red-50 p-4 text-sm font-semibold text-red-700">{error}</p>}<button disabled={sending} className="mt-7 w-full rounded-full bg-ink px-6 py-4 font-bold text-white disabled:cursor-not-allowed disabled:opacity-60">{sending?"Submitting Order...":"Order Now — Cash on Delivery"}</button></form><aside className="h-fit rounded-3xl bg-ink p-7 text-white ring-1 ring-pink-200/20"><p className="text-sm font-bold text-yellow-400">YOUR ORDER</p><h2 className="mt-3 text-xl font-bold">{productName}</h2><dl className="mt-7 space-y-4 text-sm"><Row label="Quantity" value={String(quantity)} /><Row label="Price per piece" value={formatNpr(price)} /><Row label="Delivery" value="Free inside valley" /><div className="border-t border-white/15 pt-4"><Row label="Total Price" value={formatNpr(total)} strong /></div></dl><p className="mt-7 rounded-xl bg-pink-100/10 p-4 text-sm text-white/75">Payment method: <strong className="text-white">Cash On Delivery</strong></p><p className="mt-5 text-sm text-white/65">Need help? Call 9801989840<br/>Nayathimi, Bhaktapur</p></aside></div></div></main>
}
function Field({label,name,type="text",...props}:{label:string;name:string;type?:string;required?:boolean;autoComplete?:string}){return <div><label htmlFor={name} className="mb-2 block text-sm font-bold">{label}</label><input id={name} name={name} type={type} className="w-full rounded-xl border border-black/15 px-4 py-3 outline-none ring-yellow-300 focus:ring-2" {...props}/></div>}
function Row({label,value,strong}:{label:string;value:string;strong?:boolean}){return <div className={`flex justify-between gap-3 ${strong?"text-base font-black":"text-white/70"}`}><dt>{label}</dt><dd className={strong?"":"text-right text-white"}>{value}</dd></div>}
