import { google } from "googleapis";
import nodemailer from "nodemailer";
import { NextRequest, NextResponse } from "next/server";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";

export const runtime = "nodejs";
type Order = { name: string; phone: string; email: string; location: string; productName: string; quantity: number; pricePerPiece: number; totalPrice: number };
const money = (n: number) => `Rs. ${n.toLocaleString("en-NP")}`;
const escape = (value: string | number) => String(value).replace(/[&<>'"]/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]!));
function validate(value: unknown): value is Order { if (!value || typeof value !== "object") return false; const o=value as Record<string,unknown>; return ["name","phone","email","location","productName"].every(k=>typeof o[k]==="string"&&o[k].trim()) && /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(o.email as string) && ["quantity","pricePerPiece","totalPrice"].every(k=>typeof o[k]==="number"&&Number.isFinite(o[k])&&(o[k] as number)>0); }
const requiredEnv = ["GOOGLE_SHEET_ID","BUSINESS_EMAIL","EMAIL_FROM","SMTP_HOST","SMTP_PORT","SMTP_USER","SMTP_PASS"] as const;
function googleCredentials(){ if(process.env.GOOGLE_SERVICE_ACCOUNT_JSON_PATH){const json=JSON.parse(readFileSync(resolve(process.cwd(),process.env.GOOGLE_SERVICE_ACCOUNT_JSON_PATH),"utf8")); return {email:json.client_email as string,key:(json.private_key as string)};} return {email:process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,key:process.env.GOOGLE_PRIVATE_KEY?.replace(/\\n/g,"\n")}; }
function missingConfiguration() { const missing=requiredEnv.filter(key => !process.env[key]); if(!process.env.GOOGLE_SERVICE_ACCOUNT_JSON_PATH&&(!process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL||!process.env.GOOGLE_PRIVATE_KEY)) missing.push("GOOGLE_SERVICE_ACCOUNT_JSON_PATH (or GOOGLE_SERVICE_ACCOUNT_EMAIL + GOOGLE_PRIVATE_KEY)"); return missing; }
async function appendToSheet(order: Order, id: string, date: string) { const credentials=googleCredentials(); const auth = new google.auth.JWT({ email: credentials.email, key: credentials.key, scopes:["https://www.googleapis.com/auth/spreadsheets"] }); const sheets=google.sheets({version:"v4",auth}); const tab=process.env.GOOGLE_SHEET_TAB_NAME || "Orders"; const headers=["Order ID","Date & Time","Customer Name","Phone Number","Email Address","Exact Location","Product Name","Quantity","Price Per Piece","Total Price","Payment Method","Order Status","Notes"]; const meta=await sheets.spreadsheets.get({spreadsheetId:process.env.GOOGLE_SHEET_ID!,fields:"sheets.properties"}); const sheet=meta.data.sheets?.find(s=>s.properties?.title===tab); if(sheet?.properties?.sheetId == null) throw new Error(`Google Sheet tab '${tab}' was not found.`); const current=await sheets.spreadsheets.values.get({spreadsheetId:process.env.GOOGLE_SHEET_ID!,range:`${tab}!A1:M1`}); if((current.data.values?.[0]||[]).join("|")!==headers.join("|")){await sheets.spreadsheets.values.update({spreadsheetId:process.env.GOOGLE_SHEET_ID!,range:`${tab}!A1:M1`,valueInputOption:"RAW",requestBody:{values:[headers]}}); await sheets.spreadsheets.batchUpdate({spreadsheetId:process.env.GOOGLE_SHEET_ID!,requestBody:{requests:[{updateSheetProperties:{properties:{sheetId:sheet.properties.sheetId,gridProperties:{frozenRowCount:1}},fields:"gridProperties.frozenRowCount"}},{repeatCell:{range:{sheetId:sheet.properties.sheetId,startRowIndex:0,endRowIndex:1},cell:{userEnteredFormat:{backgroundColor:{red:1,green:.68,blue:.49},textFormat:{bold:true,foregroundColor:{red:1,green:1,blue:1}},horizontalAlignment:"CENTER"}},fields:"userEnteredFormat(backgroundColor,textFormat,horizontalAlignment)"}},{autoResizeDimensions:{dimensions:{sheetId:sheet.properties.sheetId,dimension:"COLUMNS",startIndex:0,endIndex:13}}}]}}); } await sheets.spreadsheets.values.append({spreadsheetId:process.env.GOOGLE_SHEET_ID!,range:`${tab}!A:M`,valueInputOption:"USER_ENTERED",requestBody:{values:[[id,date,order.name,order.phone,order.email,order.location,order.productName,order.quantity,order.pricePerPiece,order.totalPrice,"Cash On Delivery","New Order",""]]}}); }
function emailShell(title:string,content:string){const brand=escape(process.env.BRAND_NAME||"EZVIZ");return `<!doctype html><html><body style="margin:0;background:#fffaf0;font-family:Arial,sans-serif;color:#161616"><table role="presentation" width="100%" cellpadding="0" cellspacing="0"><tr><td align="center" style="padding:28px 14px"><table role="presentation" width="100%" style="max-width:620px;background:#fff;border-radius:18px;overflow:hidden"><tr><td style="background:#161616;padding:24px 30px;color:#ffc928;font-size:24px;font-weight:800">${brand}</td></tr><tr><td style="padding:32px 30px"><h1 style="font-size:26px;margin:0 0 16px">${title}</h1>${content}</td></tr><tr><td style="padding:18px 30px;background:#f6f1e7;color:#777;font-size:12px">Ã‚Â© ${new Date().getFullYear()} ${brand}</td></tr></table></td></tr></table></body></html>`}
const line=(label:string,value:string|number)=>`<tr><td style="padding:9px 0;color:#777">${label}</td><td style="padding:9px 0;text-align:right;font-weight:700">${escape(value)}</td></tr>`;
async function sendEmails(order:Order,id:string,date:string){const transporter=nodemailer.createTransport({host:process.env.SMTP_HOST,port:Number(process.env.SMTP_PORT),secure:Number(process.env.SMTP_PORT)===465,auth:{user:process.env.SMTP_USER,pass:process.env.SMTP_PASS}}); const details=`<table width="100%" style="border-collapse:collapse">${line("Order ID",id)}${line("Date & time",date)}${line("Customer",order.name)}${line("Phone",order.phone)}${line("Email",order.email)}${line("Location",order.location)}${line("Product",order.productName)}${line("Quantity",order.quantity)}${line("Price per piece",money(order.pricePerPiece))}${line("Total",money(order.totalPrice))}${line("Payment","Cash On Delivery")}${line("Status","New Order")}</table>`; await transporter.sendMail({from:process.env.EMAIL_FROM,to:process.env.BUSINESS_EMAIL,replyTo:process.env.EMAIL_FROM,subject:`New Product Order Received - ${id}`,html:emailShell("New order received",`${details}<p style="margin:24px 0 0;padding:14px;background:#fff4c8;border-radius:10px;font-weight:700">Please call the customer soon to confirm this order.</p>`)}); await transporter.sendMail({from:process.env.EMAIL_FROM,to:order.email,replyTo:process.env.EMAIL_FROM,subject:`Your Order Has Been Received - ${process.env.BRAND_NAME||"EZVIZ"}`,html:emailShell(`Thank you, ${escape(order.name)}!`,`<p>We have received your order successfully.</p>${details}<p style="margin-top:22px;padding:14px;background:#fff4c8;border-radius:10px">Our sales representative will call you soon to confirm your order.</p><p style="color:#666">Questions? Reply to this email and our team will be happy to help.</p><p>Thank you,<br><strong>${escape(process.env.BRAND_NAME||"EZVIZ")}</strong></p>`)}); }
export async function POST(req:NextRequest){try { const missing = missingConfiguration(); if(missing.length) return NextResponse.json({error:`Order service setup is incomplete. Missing: ${missing.join(", ")}. Add these values to .env.local and restart the server.`},{status:503}); const data:unknown=await req.json(); if(!validate(data)) return NextResponse.json({error:"Please provide a valid name, phone, email, location, product, quantity, and price."},{status:400}); const order=data as Order; const id=`EZ-${Date.now().toString(36).toUpperCase()}-${Math.random().toString(36).slice(2,6).toUpperCase()}`; const date=new Intl.DateTimeFormat("en-NP",{dateStyle:"medium",timeStyle:"short",timeZone:"Asia/Kathmandu"}).format(new Date()); await appendToSheet(order,id,date); await sendEmails(order,id,date); return NextResponse.json({success:true,orderId:id}); } catch(error){console.error("Order submission failed:",error); return NextResponse.json({error:"We could not submit your order. Please check your details and try again."},{status:500});}}
